### ISSUE TITLE
⬅️ tutorial walkthrough for creating a simple app

### ISSUE THREAD

**Issue by jalium** [flojoy-ai/docs#19]
TO DO: Choose an appropriate app for this tutorial section

**Comment by jackparmer** [comment]
I think that we could just generate and plot a normal distribution as a histogram, using default parameters. This would be only 2 nodes.

Like this:
https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html

what do you think @trbritt @Angchau @dstrande - is this a good "hello world" example to start off our tutorials on the docs?

**Comment by dstrande** [comment]
Right now my camera example walks through adding nodes, parameters/ctrls, and other things.

But it could be served by adding a simple example like this that doesn't need a camera/any DAQ.

**Comment by trbritt** [comment]
We could do some (potentially paired down) version of the default app that loads when Flojoy boots? That would be a nice example that includes 'builtin' nodes only (I'm thinking of something like how Blender loads the default cube on start-up).

**Comment by Angchau** [comment]
Yes I agree with you guys, I think it's a good idea to start with a very classical histogram plot which using only 2 nodes so the user can get familiar with the management of the parameters and the plots. The user will understand how to generate and plot data with the app which I think it's pretty good. But for me this should go in a general tutorial for the app, and then if the user wants to use a specific instrument, he'll have a more precise description on how the specific node for this Instrument is working (What data it takes and what data it returns).

**Comment by dstrande** [comment]
I've gotten started on this (WIP):

https://docs.flojoy.io/tutorial/introduction/

Laying out the UI and then showing how to create an app.

**Comment by dstrande** [comment]
https://docs.flojoy.io/tutorial/introduction/

Take a look @jackparmer @jalium
