### ISSUE TITLE
Automate the creation of Node docs

### ISSUE THREAD

**Issue by scorinaldi** [flojoy-ai/docs#33]
We should be pulling the python code, and docstring portion of the docs at the very least. 

Ideally, we'd autogenerate every little thing we need to for a given node's docs. (Examples might be tricky)

**Comment by jackparmer** [comment]
I don't think that we can (or should) autogenerate examples or anything below that

But the code, docstring description, and parameters are obviously machine-readable and designed with doc autogeneration in mind - so let's prioritize autogenerating that first section
